# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics


on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: OfficialCodeVoyage
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_octicon: yes
          config_timezone: America/Chicago
          config_twemoji: yes
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_other: yes
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_leetcode: yes
          plugin_leetcode_limit_recent: 2
          plugin_leetcode_limit_skills: 10
          plugin_leetcode_sections: solved
          plugin_leetcode_user: officialcodevoyage


name: Metrics Workflow

on:
  push:
    branches:
      - main  # ou qualquer outra branch de sua escolha
  pull_request:
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-latest  # Ou outra versão do sistema operacional desejada

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # ou qualquer versão que você use

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Adapte de acordo com seu projeto

      - name: Run metrics script
        run: |
          python path/to/your/metrics_script.py  # Execute o script que gera as métricas

      - name: Upload metrics to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: metrics
          path: path/to/metrics/results.csv  # Exemplo de onde os resultados podem ser armazenados
